import { COATemplate } from '@/types/accounting';

export const COA_TEMPLATES: COATemplate[] = [
  {
    id: 'standard',
    name: 'Standard Business',
    description: 'Suitable for most businesses — covers common revenue, expense, asset, and liability accounts.',
    accounts: [
      // Assets
      { code: '1000', name: 'Cash at Bank', type: 'asset', sub_type: 'current_asset', is_system: true },
      { code: '1010', name: 'Petty Cash', type: 'asset', sub_type: 'current_asset' },
      { code: '1100', name: 'Accounts Receivable', type: 'asset', sub_type: 'current_asset', is_system: true },
      { code: '1150', name: 'Prepayments', type: 'asset', sub_type: 'current_asset' },
      { code: '1200', name: 'Inventory', type: 'asset', sub_type: 'current_asset' },
      { code: '1300', name: 'GST Receivable', type: 'asset', sub_type: 'current_asset', is_system: true },
      { code: '1500', name: 'Office Equipment', type: 'asset', sub_type: 'fixed_asset' },
      { code: '1510', name: 'Computer Equipment', type: 'asset', sub_type: 'fixed_asset' },
      { code: '1520', name: 'Furniture & Fixtures', type: 'asset', sub_type: 'fixed_asset' },
      { code: '1530', name: 'Motor Vehicles', type: 'asset', sub_type: 'fixed_asset' },
      { code: '1600', name: 'Accumulated Depreciation', type: 'asset', sub_type: 'fixed_asset' },
      // Liabilities
      { code: '2000', name: 'Accounts Payable', type: 'liability', sub_type: 'current_liability', is_system: true },
      { code: '2050', name: 'Credit Card', type: 'liability', sub_type: 'current_liability' },
      { code: '2100', name: 'GST Payable', type: 'liability', sub_type: 'current_liability', is_system: true },
      { code: '2110', name: 'PAYG Withholding', type: 'liability', sub_type: 'current_liability' },
      { code: '2120', name: 'Superannuation Payable', type: 'liability', sub_type: 'current_liability' },
      { code: '2130', name: 'Wages Payable', type: 'liability', sub_type: 'current_liability' },
      { code: '2200', name: 'Income in Advance', type: 'liability', sub_type: 'current_liability' },
      { code: '2500', name: 'Business Loan', type: 'liability', sub_type: 'non_current_liability' },
      // Equity
      { code: '3000', name: 'Owner\'s Equity', type: 'equity', sub_type: 'equity', is_system: true },
      { code: '3100', name: 'Retained Earnings', type: 'equity', sub_type: 'equity', is_system: true },
      { code: '3200', name: 'Owner\'s Drawings', type: 'equity', sub_type: 'equity' },
      // Revenue
      { code: '4000', name: 'Sales Revenue', type: 'revenue', sub_type: 'operating_revenue', is_system: true },
      { code: '4100', name: 'Service Revenue', type: 'revenue', sub_type: 'operating_revenue' },
      { code: '4200', name: 'Interest Income', type: 'revenue', sub_type: 'other_revenue' },
      { code: '4300', name: 'Other Revenue', type: 'revenue', sub_type: 'other_revenue' },
      { code: '4400', name: 'Discount Received', type: 'revenue', sub_type: 'other_revenue' },
      // Expenses
      { code: '5000', name: 'Cost of Goods Sold', type: 'expense', sub_type: 'direct_cost' },
      { code: '5100', name: 'Purchase Discounts', type: 'expense', sub_type: 'direct_cost' },
      { code: '6000', name: 'Advertising & Marketing', type: 'expense', sub_type: 'operating_expense' },
      { code: '6010', name: 'Bank Fees', type: 'expense', sub_type: 'operating_expense' },
      { code: '6020', name: 'Cleaning', type: 'expense', sub_type: 'operating_expense' },
      { code: '6030', name: 'Consulting & Accounting', type: 'expense', sub_type: 'operating_expense' },
      { code: '6040', name: 'Depreciation', type: 'expense', sub_type: 'operating_expense' },
      { code: '6050', name: 'Entertainment', type: 'expense', sub_type: 'operating_expense' },
      { code: '6060', name: 'Freight & Courier', type: 'expense', sub_type: 'operating_expense' },
      { code: '6070', name: 'General Expenses', type: 'expense', sub_type: 'operating_expense' },
      { code: '6080', name: 'Insurance', type: 'expense', sub_type: 'operating_expense' },
      { code: '6090', name: 'Interest Expense', type: 'expense', sub_type: 'operating_expense' },
      { code: '6100', name: 'Legal Expenses', type: 'expense', sub_type: 'operating_expense' },
      { code: '6110', name: 'Motor Vehicle Expenses', type: 'expense', sub_type: 'operating_expense' },
      { code: '6120', name: 'Office Supplies', type: 'expense', sub_type: 'operating_expense' },
      { code: '6130', name: 'Printing & Stationery', type: 'expense', sub_type: 'operating_expense' },
      { code: '6140', name: 'Rent', type: 'expense', sub_type: 'operating_expense' },
      { code: '6150', name: 'Repairs & Maintenance', type: 'expense', sub_type: 'operating_expense' },
      { code: '6160', name: 'Software & Subscriptions', type: 'expense', sub_type: 'operating_expense' },
      { code: '6170', name: 'Telephone & Internet', type: 'expense', sub_type: 'operating_expense' },
      { code: '6180', name: 'Travel & Accommodation', type: 'expense', sub_type: 'operating_expense' },
      { code: '6190', name: 'Utilities', type: 'expense', sub_type: 'operating_expense' },
      { code: '6200', name: 'Wages & Salaries', type: 'expense', sub_type: 'operating_expense' },
      { code: '6210', name: 'Superannuation', type: 'expense', sub_type: 'operating_expense' },
    ],
  },
  {
    id: 'service',
    name: 'Service Business',
    description: 'Optimised for service companies — fewer inventory accounts, more project & fee categories.',
    accounts: [
      { code: '1000', name: 'Cash at Bank', type: 'asset', sub_type: 'current_asset', is_system: true },
      { code: '1010', name: 'Petty Cash', type: 'asset', sub_type: 'current_asset' },
      { code: '1100', name: 'Accounts Receivable', type: 'asset', sub_type: 'current_asset', is_system: true },
      { code: '1150', name: 'Prepayments', type: 'asset', sub_type: 'current_asset' },
      { code: '1300', name: 'GST Receivable', type: 'asset', sub_type: 'current_asset', is_system: true },
      { code: '1500', name: 'Office Equipment', type: 'asset', sub_type: 'fixed_asset' },
      { code: '1510', name: 'Computer Equipment', type: 'asset', sub_type: 'fixed_asset' },
      { code: '1600', name: 'Accumulated Depreciation', type: 'asset', sub_type: 'fixed_asset' },
      { code: '2000', name: 'Accounts Payable', type: 'liability', sub_type: 'current_liability', is_system: true },
      { code: '2100', name: 'GST Payable', type: 'liability', sub_type: 'current_liability', is_system: true },
      { code: '2110', name: 'PAYG Withholding', type: 'liability', sub_type: 'current_liability' },
      { code: '2120', name: 'Superannuation Payable', type: 'liability', sub_type: 'current_liability' },
      { code: '2130', name: 'Wages Payable', type: 'liability', sub_type: 'current_liability' },
      { code: '2200', name: 'Income in Advance', type: 'liability', sub_type: 'current_liability' },
      { code: '3000', name: 'Owner\'s Equity', type: 'equity', sub_type: 'equity', is_system: true },
      { code: '3100', name: 'Retained Earnings', type: 'equity', sub_type: 'equity', is_system: true },
      { code: '3200', name: 'Owner\'s Drawings', type: 'equity', sub_type: 'equity' },
      { code: '4000', name: 'Consulting Revenue', type: 'revenue', sub_type: 'operating_revenue', is_system: true },
      { code: '4100', name: 'Service Revenue', type: 'revenue', sub_type: 'operating_revenue' },
      { code: '4200', name: 'Project Revenue', type: 'revenue', sub_type: 'operating_revenue' },
      { code: '4300', name: 'Retainer Revenue', type: 'revenue', sub_type: 'operating_revenue' },
      { code: '4400', name: 'Interest Income', type: 'revenue', sub_type: 'other_revenue' },
      { code: '5000', name: 'Contractor Costs', type: 'expense', sub_type: 'direct_cost' },
      { code: '5100', name: 'Project Materials', type: 'expense', sub_type: 'direct_cost' },
      { code: '6000', name: 'Advertising & Marketing', type: 'expense', sub_type: 'operating_expense' },
      { code: '6010', name: 'Bank Fees', type: 'expense', sub_type: 'operating_expense' },
      { code: '6030', name: 'Professional Fees', type: 'expense', sub_type: 'operating_expense' },
      { code: '6040', name: 'Depreciation', type: 'expense', sub_type: 'operating_expense' },
      { code: '6080', name: 'Insurance', type: 'expense', sub_type: 'operating_expense' },
      { code: '6120', name: 'Office Supplies', type: 'expense', sub_type: 'operating_expense' },
      { code: '6140', name: 'Rent', type: 'expense', sub_type: 'operating_expense' },
      { code: '6160', name: 'Software & Subscriptions', type: 'expense', sub_type: 'operating_expense' },
      { code: '6170', name: 'Telephone & Internet', type: 'expense', sub_type: 'operating_expense' },
      { code: '6180', name: 'Travel & Accommodation', type: 'expense', sub_type: 'operating_expense' },
      { code: '6200', name: 'Wages & Salaries', type: 'expense', sub_type: 'operating_expense' },
      { code: '6210', name: 'Superannuation', type: 'expense', sub_type: 'operating_expense' },
    ],
  },
  {
    id: 'retail',
    name: 'Retail Business',
    description: 'Built for shops and retail — includes inventory, COGS, and POS-related accounts.',
    accounts: [
      { code: '1000', name: 'Cash at Bank', type: 'asset', sub_type: 'current_asset', is_system: true },
      { code: '1010', name: 'Cash on Hand / Till', type: 'asset', sub_type: 'current_asset' },
      { code: '1100', name: 'Accounts Receivable', type: 'asset', sub_type: 'current_asset', is_system: true },
      { code: '1200', name: 'Inventory', type: 'asset', sub_type: 'current_asset' },
      { code: '1300', name: 'GST Receivable', type: 'asset', sub_type: 'current_asset', is_system: true },
      { code: '1500', name: 'Shop Fittings', type: 'asset', sub_type: 'fixed_asset' },
      { code: '1510', name: 'Computer & POS Equipment', type: 'asset', sub_type: 'fixed_asset' },
      { code: '1600', name: 'Accumulated Depreciation', type: 'asset', sub_type: 'fixed_asset' },
      { code: '2000', name: 'Accounts Payable', type: 'liability', sub_type: 'current_liability', is_system: true },
      { code: '2050', name: 'Credit Card', type: 'liability', sub_type: 'current_liability' },
      { code: '2100', name: 'GST Payable', type: 'liability', sub_type: 'current_liability', is_system: true },
      { code: '2110', name: 'PAYG Withholding', type: 'liability', sub_type: 'current_liability' },
      { code: '2120', name: 'Superannuation Payable', type: 'liability', sub_type: 'current_liability' },
      { code: '2130', name: 'Wages Payable', type: 'liability', sub_type: 'current_liability' },
      { code: '3000', name: 'Owner\'s Equity', type: 'equity', sub_type: 'equity', is_system: true },
      { code: '3100', name: 'Retained Earnings', type: 'equity', sub_type: 'equity', is_system: true },
      { code: '3200', name: 'Owner\'s Drawings', type: 'equity', sub_type: 'equity' },
      { code: '4000', name: 'Product Sales', type: 'revenue', sub_type: 'operating_revenue', is_system: true },
      { code: '4100', name: 'Shipping Revenue', type: 'revenue', sub_type: 'operating_revenue' },
      { code: '4200', name: 'Interest Income', type: 'revenue', sub_type: 'other_revenue' },
      { code: '5000', name: 'Cost of Goods Sold', type: 'expense', sub_type: 'direct_cost', is_system: true },
      { code: '5010', name: 'Purchase Discounts', type: 'expense', sub_type: 'direct_cost' },
      { code: '5020', name: 'Freight Inward', type: 'expense', sub_type: 'direct_cost' },
      { code: '5030', name: 'Inventory Write-off', type: 'expense', sub_type: 'direct_cost' },
      { code: '6000', name: 'Advertising & Marketing', type: 'expense', sub_type: 'operating_expense' },
      { code: '6010', name: 'Bank & Merchant Fees', type: 'expense', sub_type: 'operating_expense' },
      { code: '6040', name: 'Depreciation', type: 'expense', sub_type: 'operating_expense' },
      { code: '6060', name: 'Freight & Delivery', type: 'expense', sub_type: 'operating_expense' },
      { code: '6080', name: 'Insurance', type: 'expense', sub_type: 'operating_expense' },
      { code: '6100', name: 'Packaging', type: 'expense', sub_type: 'operating_expense' },
      { code: '6140', name: 'Rent', type: 'expense', sub_type: 'operating_expense' },
      { code: '6150', name: 'Repairs & Maintenance', type: 'expense', sub_type: 'operating_expense' },
      { code: '6160', name: 'Software & Subscriptions', type: 'expense', sub_type: 'operating_expense' },
      { code: '6190', name: 'Utilities', type: 'expense', sub_type: 'operating_expense' },
      { code: '6200', name: 'Wages & Salaries', type: 'expense', sub_type: 'operating_expense' },
      { code: '6210', name: 'Superannuation', type: 'expense', sub_type: 'operating_expense' },
    ],
  },
];

export const DEFAULT_TAX_RATES = [
  { name: 'GST (10%)', rate: 10, is_default: true },
  { name: 'GST Free', rate: 0, is_default: false },
  { name: 'BAS Excluded', rate: 0, is_default: false },
];

export const CURRENCY_OPTIONS = [
  { value: 'AUD', label: 'AUD — Australian Dollar' },
  { value: 'USD', label: 'USD — US Dollar' },
  { value: 'GBP', label: 'GBP — British Pound' },
  { value: 'EUR', label: 'EUR — Euro' },
  { value: 'NZD', label: 'NZD — New Zealand Dollar' },
  { value: 'CAD', label: 'CAD — Canadian Dollar' },
  { value: 'NPR', label: 'NPR — Nepalese Rupee' },
  { value: 'INR', label: 'INR — Indian Rupee' },
  { value: 'SGD', label: 'SGD — Singapore Dollar' },
  { value: 'HKD', label: 'HKD — Hong Kong Dollar' },
];
